//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platom.Protocol.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Platom.Protocol.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;sequence&quot;: {
        ///    &quot;timestamp&quot;: &quot;2019-11-12T11:22:33Z&quot;,
        ///    &quot;number&quot;: 1423234,
        ///    &quot;channel&quot;: &quot;et3_measurements&quot;,
        ///    &quot;service&quot;: &quot;ET3&quot;,
        ///    &quot;schema&quot;: &quot;ect_potentials&quot;
        ///  },
        ///  &quot;payload&quot;: {
        ///    &quot;electrodes&quot;: 8,
        ///    &quot;potentials&quot;: {
        ///      &quot;rows&quot;: 7,
        ///      &quot;cols&quot;: 7,
        ///      &quot;data&quot;: [
        ///        [12.00, 13.00, 14.00, 15.00, 16.00, 17.00, 18.00],
        ///        [23.00, 24.00, 25.00, 26.00, 27.00, 28.00],
        ///        [34.00, 35.00, 36.00, 37.00, 38.00],
        ///        [45.00, 46.00, 47.00, 48.00],
        ///        [56.00, 57. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string message_et3_measurements {
            get {
                return ResourceManager.GetString("message_et3_measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;sequence&quot;: {
        ///    &quot;timestamp&quot;: &quot;2020-03-26T21:42:32.4237529+01:00&quot;,
        ///    &quot;number&quot;: 1,
        ///    &quot;channel&quot;: &quot;status&quot;,
        ///    &quot;service&quot;: &quot;Zegarynka&quot;,
        ///    &quot;schema&quot;: &quot;schema_status&quot;
        ///  },
        ///  &quot;payload&quot;: {
        ///    &quot;service&quot;: &quot;Zegarynka&quot;,
        ///    &quot;publishes&quot;: [&quot;DateChannel&quot;, &quot;TimeChannel&quot;],
        ///    &quot;subscribes&quot;: [],
        ///    &quot;next_alive_interval&quot;: 7000,
        ///    &quot;timeout&quot;: 10000
        ///  }
        ///}.
        /// </summary>
        public static string message_status {
            get {
                return ResourceManager.GetString("message_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;header&quot;: {
        ///    &quot;name&quot;: &quot;ect_potentials&quot;,
        ///    &quot;service&quot;: &quot;ET3&quot;,
        ///    &quot;channel&quot;: &quot;et3_measurements&quot;,
        ///    &quot;description&quot;: &quot;jakiś opis tekstowy; dowolny&quot;,
        ///    &quot;mapping&quot;: {
        ///      //&quot;table&quot;: &quot;nazwa tabeli w bazie danych&quot;
        ///    
        ///    }
        ///  },
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;electrodes&quot;,
        ///      &quot;description&quot;: &quot;Liczba elektrod wykorzystana w danym pomiarze&quot;,
        ///      &quot;type&quot;: {
        ///        &quot;name&quot;: &quot;integer&quot;,
        ///        &quot;minimum&quot;: 2,
        ///        &quot;maximum&quot;: 64
        ///      },
        ///      &quot;mapping&quot;: {
        ///        //&quot;column&quot;: &quot;ele [rest of string was truncated]&quot;;.
        /// </summary>
        public static string schema_ect_potentials {
            get {
                return ResourceManager.GetString("schema_ect_potentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;header&quot;: {
        ///    &quot;name&quot;: &quot;schema_status&quot;, // nazwa schematu walidacyjnego
        ///    &quot;service&quot;: null, // nazwa usługi generującej komunikaty
        ///    &quot;channel&quot;: &quot;status&quot;, // nazwa kanału, jakim dany komunikat jest przesyłany
        ///    &quot;description&quot;: &quot;jakiś opis tekstowy; dowolny&quot;,
        ///    &quot;mapping&quot;: {
        ///      //&quot;table&quot;: &quot;nazwa tabeli w bazie danych&quot;
        ///
        ///    }
        ///  },
        ///
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;service&quot;,
        ///      &quot;description&quot;: &quot;Nazwa usługi generującej komunikat, nadawany kanałem status&quot;,
        ///      &quot;type&quot;: {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string schema_status {
            get {
                return ResourceManager.GetString("schema_status", resourceCulture);
            }
        }
    }
}
